<script lang="ts">
  import { page } from '$app/state';
  import type { Game, GameFilters, Offer, Store } from '$lib/domain/models';
  import { gameRepository } from '$lib/data/mock-repository';
  import { bestThaiOffer, discountPercent } from '$lib/domain/pricing';
  import ResultRow from './ResultRow.svelte';
  import FilterPanel from '$lib/components/filters/FilterPanel.svelte';
  import EmptyState from '$lib/components/ui/EmptyState.svelte';
  let { popular = false }: { popular?: boolean } = $props();
  type Entry = { game: Game; offer: Offer; store: Store };
  let entries = $state<Entry[]>([]), loading = $state(true), sort = $state('final'), sheet = $state<'filter'|'sort'|null>(null);
  let filters = $state<GameFilters>({thailandOnly:true,officialOnly:false,excludeMarketplace:false,inStockOnly:true,historicalLowOnly:false,maxPriceSatang:240000,minDiscountPercent:0});
  const query = $derived(popular ? '*' : (page.url.searchParams.get('q') ?? 'The Forest'));
  $effect(()=>{const current=query;loading=true;Promise.all([gameRepository.listGames(),gameRepository.listStores()]).then(async([allGames,stores])=>{const selected=current==='*'?allGames:allGames.filter(game=>game.title.toLowerCase().includes(current.toLowerCase()));const built=await Promise.all(selected.map(async game=>{const offer=bestThaiOffer(await gameRepository.getOffers(game.slug));return offer?{game,offer,store:stores.find(store=>store.id===offer.storeId)??stores[0]}:null}));entries=built.filter((item):item is Entry=>item!==null);loading=false})});
  const shown=$derived.by(()=>entries.filter(entry=>entry.offer.finalSatang<=filters.maxPriceSatang&&discountPercent(entry.offer)>=filters.minDiscountPercent&&(!filters.officialOnly||['official','steam'].includes(entry.store.type))&&(!filters.excludeMarketplace||entry.store.type!=='marketplace')&&(!filters.inStockOnly||entry.offer.inStock)).sort((a,b)=>sort==='final'?a.offer.finalSatang-b.offer.finalSatang:sort==='discount'?discountPercent(b.offer)-discountPercent(a.offer):sort==='popular'?b.game.popularity-a.game.popularity:sort==='release'?b.game.year-a.game.year:a.game.title.localeCompare(b.game.title)));
  const reset=()=>filters={thailandOnly:false,officialOnly:false,excludeMarketplace:false,inStockOnly:true,historicalLowOnly:false,maxPriceSatang:240000,minDiscountPercent:0};
  const filterCount=$derived([filters.thailandOnly,filters.officialOnly,filters.excludeMarketplace,filters.historicalLowOnly,filters.minDiscountPercent>0,filters.maxPriceSatang<240000].filter(Boolean).length);
  const sortLabels:Record<string,string>={final:'ราคาต่ำสุด',discount:'ส่วนลดมากที่สุด',popular:'ความนิยม',release:'วันวางจำหน่าย',updated:'อัปเดตล่าสุด'};
  $effect(() => { if (popular && sort === 'final') sort = 'popular'; });
</script>
<main class="page"><header class="intro"><div><h1>{popular?'เกมยอดนิยม':`ผลการค้นหา “${query}”`} <small>{loading?'กำลังค้นหา…':`พบ ${shown.length} เกม`}</small></h1><p>ราคาที่แสดงคือราคาสุทธิโดยประมาณต่ำสุดที่ยืนยันว่าเปิดใช้งานในไทยได้ · อัปเดตล่าสุด 2 ส.ค. 2569 · 14:32 น.</p></div></header><div class="layout"><aside><FilterPanel bind:filters onreset={reset}/></aside><section class="results"><div class="controls"><div class="mobile-buttons"><button class="btn" onclick={()=>sheet='filter'}>☷ ตัวกรอง {#if filterCount}<b>{filterCount}</b>{/if}</button><button class="btn" onclick={()=>sheet='sort'}>⇅ {sortLabels[sort]}</button></div><span class="count">{shown.length} เกม</span><label>เรียงตาม <select bind:value={sort}><option value="final">ราคาต่ำสุด</option><option value="discount">ส่วนลดมากที่สุด</option><option value="popular">ความนิยม</option><option value="release">วันวางจำหน่าย</option><option value="updated">อัปเดตล่าสุด</option></select></label></div>
  {#if filterCount}<div class="pills">{#if filters.thailandOnly}<button onclick={()=>filters={...filters,thailandOnly:false}}>ใช้งานได้ในประเทศไทย ×</button>{/if}{#if filters.officialOnly}<button onclick={()=>filters={...filters,officialOnly:false}}>ร้านค้าอย่างเป็นทางการ ×</button>{/if}{#if filters.excludeMarketplace}<button onclick={()=>filters={...filters,excludeMarketplace:false}}>ไม่รวม Marketplace ×</button>{/if}<button onclick={reset}>ล้างทั้งหมด</button></div>{/if}
  {#if loading}<div class="skeletons">{#each [1,2,3,4] as item}<div style={`animation-delay:${item*.08}s`}></div>{/each}</div>{:else if !shown.length}<EmptyState kind="no-results" query={query==='*'?'ตัวกรองที่เลือก':query} action={reset}/>{:else}<div class="rows">{#each shown as entry}<ResultRow {...entry}/>{/each}</div>{/if}</section></div></main>
{#if sheet}<div class="backdrop" role="presentation" onclick={(event)=>{if(event.target===event.currentTarget)sheet=null}}><section class="sheet"><i></i><header><h2>{sheet==='filter'?'ตัวกรอง':'เรียงตาม'}</h2><button onclick={()=>sheet=null}>×</button></header>{#if sheet==='filter'}<div class="sheet-body"><FilterPanel bind:filters bare onreset={reset}/></div><button class="apply" onclick={()=>sheet=null}>ดูผลลัพธ์ {shown.length} เกม</button>{:else}<div class="sorts">{#each Object.entries(sortLabels) as option}<button class:active={sort===option[0]} onclick={()=>{sort=option[0];sheet=null}}>{option[1]} {#if sort===option[0]}✓{/if}</button>{/each}</div>{/if}</section></div>{/if}
<style>.intro h1{font-size:27px}.intro h1 small{margin-left:8px;color:var(--mute);font-size:13px;font-weight:400}.intro p{margin:5px 0 20px;color:var(--mute2);font-size:12.5px}.layout{display:flex;align-items:flex-start;gap:22px}.layout>aside{position:sticky;top:82px;width:246px;flex:none}.results{min-width:0;flex:1}.controls{display:flex;align-items:center;gap:10px;margin-bottom:14px}.count{margin-right:auto;color:var(--mute2);font-size:12px}.controls label{display:flex;align-items:center;gap:8px;color:var(--mute);font-size:12.5px}.controls select{min-height:34px;padding:0 30px 0 10px;border:1px solid var(--line);border-radius:8px;background:var(--color-surface);color:var(--ink)}.mobile-buttons{display:none}.pills{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:14px}.pills button{padding:4px 9px;border:1px solid color-mix(in srgb,var(--color-accent) 40%,transparent);border-radius:999px;background:color-mix(in srgb,var(--color-accent) 12%,transparent);color:var(--color-accent-300);font-size:11.5px}.pills button:last-child{border-color:transparent;background:transparent;color:var(--mute);text-decoration:underline}.rows,.skeletons{display:flex;flex-direction:column;gap:10px}.skeletons div{height:132px;border:1px solid var(--line2);border-radius:13px;background:linear-gradient(100deg,#1b1e2c 30%,#23273a 50%,#1b1e2c 70%);background-size:720px 100%;animation:shimmer 1.25s infinite}.backdrop{position:fixed;inset:0;z-index:70;display:none;align-items:flex-end;background:rgb(9 11 18 / 66%);backdrop-filter:blur(3px)}.sheet{width:100%;max-height:86%;overflow:auto;border:1px solid var(--line);border-radius:20px 20px 0 0;background:var(--raise);animation:rise .2s}.sheet>i{display:block;width:38px;height:4px;margin:10px auto;border-radius:99px;background:#3d4054}.sheet header{display:flex;justify-content:space-between;padding:4px 16px 12px;border-bottom:1px solid var(--line2)}.sheet header h2{font-size:16px}.sheet header button{border:0;background:none;color:var(--muted);font-size:20px}.sheet-body{padding:14px 16px}.apply{position:sticky;bottom:0;width:calc(100% - 32px);height:48px;margin:0 16px 14px;border:1px solid var(--color-accent);border-radius:12px;background:var(--raise);color:var(--color-accent-200);font-weight:600}.sorts button{display:flex;justify-content:space-between;width:100%;padding:15px 18px;border:0;border-top:1px solid var(--line2);background:transparent;color:var(--ink);text-align:left}.sorts button.active{color:var(--color-accent-200)}@media(max-width:779px){.intro h1{font-size:21px}.layout>aside,.controls>.count,.controls>label{display:none}.mobile-buttons{display:flex;width:100%;gap:10px}.mobile-buttons button{flex:1}.mobile-buttons b{min-width:17px;border-radius:99px;background:var(--color-accent);color:var(--color-bg)}.backdrop{display:flex}}</style>
