/**
 * Cloudflare Worker bindings. `D1Database` comes from the ambient runtime
 * types generated by `pnpm wrangler types` into `worker-configuration.d.ts`.
 */
export interface Bindings {
  DB: D1Database
}
